# Generated by Django 2.2.5 on 2019-12-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pubblish_date',
            new_name='published_date',
        ),
    ]
